name: "Setup Environment"
description: "Check out code, set up Node, and install pnpm dependencies"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
