allowBuilds:
  cpu-features: true
  esbuild: false
  protobufjs: false
  sharp: false
  ssh2: true
  workerd: false
# minimumReleaseAge: 1440
minimumReleaseAge: 0

blockExoticSubdeps: false

catalogs:
  drizzle:
    drizzle-orm: 1.0.0-rc.4
    drizzle-kit: 1.0.0-rc.4

  auth:
    "@better-auth-ui/core": 1.7.16
    "@better-auth-ui/react": 1.7.16
    "@better-auth-ui/locales": 1.7.16

    "auth": 1.7.2
    "better-auth": 1.7.2
    "@better-auth/drizzle-adapter": 1.7.2
    "@better-auth/passkey": 1.7.2
    "@better-auth/i18n": 1.7.2

overrides:
  drizzle-orm: catalog:drizzle
