export const STANDARD_MEASUREMENT_NAMES = [
  "Contorno cuello",
  "Ancho espalda",
  "Talle delantero",
  "Talle trasero",
  "Alto busto",
  "Separación busto",
  "Alto escote",
  "Contorno tórax",
  "Contorno busto",
  "Contorno cintura",
  "Contorno cadera",
  "Alto cadera",
  "Largo brazo",
  "Largo manga",
  "Largo camisa",
  "Largo chaqueta",
  "Contorno de brazo",
  "Contorno de muñeca",
  "Largo falda",
  "Largo pantalón",
  "Contorno rodilla",
  "Contorno bota",
] as const;
