/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppAppRouteRouteImport } from './routes/_app/app/route'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as AppAppWorkspaceRouteRouteImport } from './routes/_app/app/_workspace/route'
import { Route as AppAppOnboardingRouteImport } from './routes/_app/app/onboarding'
import { Route as AppAuthPathRouteImport } from './routes/_app/auth.$path'
import { Route as AppOrganizationPathRouteImport } from './routes/_app/organization.$path'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppAppWorkspaceIndexRouteImport } from './routes/_app/app/_workspace/index'
import { Route as AppAppAdminPathRouteImport } from './routes/_app/app/admin.$path'
import { Route as AppAppSettingsPathRouteImport } from './routes/_app/app/settings.$path'
import { Route as AppAppWorkspaceClientsIndexRouteImport } from './routes/_app/app/_workspace/clients.index'
import { Route as AppAppWorkspaceClientsIdRouteImport } from './routes/_app/app/_workspace/clients.$id'
import { Route as AppAppWorkspaceGarmentsIndexRouteImport } from './routes/_app/app/_workspace/garments.index'
import { Route as AppAppWorkspaceGarmentsSlugRouteImport } from './routes/_app/app/_workspace/garments.$slug'
import { Route as AppAppWorkspaceMaterialsIndexRouteImport } from './routes/_app/app/_workspace/materials.index'
import { Route as AppAppWorkspaceMaterialsIdRouteImport } from './routes/_app/app/_workspace/materials.$id'
import { Route as AppAppWorkspaceOperationsIndexRouteImport } from './routes/_app/app/_workspace/operations.index'
import { Route as AppAppWorkspaceOrdersIndexRouteImport } from './routes/_app/app/_workspace/orders.index'
import { Route as AppAppWorkspaceOrdersCodeRouteImport } from './routes/_app/app/_workspace/orders.$code'
import { Route as AppAppWorkspaceOrdersNewRouteImport } from './routes/_app/app/_workspace/orders.new'
import { Route as AppAppWorkspaceOrdersStagesRouteImport } from './routes/_app/app/_workspace/orders.stages'
import { Route as AppAppWorkspaceQuotationsIndexRouteImport } from './routes/_app/app/_workspace/quotations.index'
import { Route as AppAppWorkspaceQuotationsSlugRouteImport } from './routes/_app/app/_workspace/quotations.$slug'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRouteRoute = AppAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRouteRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppWorkspaceRouteRoute = AppAppWorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppOnboardingRoute = AppAppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAuthPathRoute = AppAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationPathRoute = AppOrganizationPathRouteImport.update({
  id: '/organization/$path',
  path: '/organization/$path',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppWorkspaceIndexRoute = AppAppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppWorkspaceRouteRoute,
} as any)
const AppAppAdminPathRoute = AppAppAdminPathRouteImport.update({
  id: '/admin/$path',
  path: '/admin/$path',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppSettingsPathRoute = AppAppSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppWorkspaceClientsIndexRoute =
  AppAppWorkspaceClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceClientsIdRoute =
  AppAppWorkspaceClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceGarmentsIndexRoute =
  AppAppWorkspaceGarmentsIndexRouteImport.update({
    id: '/garments/',
    path: '/garments/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceGarmentsSlugRoute =
  AppAppWorkspaceGarmentsSlugRouteImport.update({
    id: '/garments/$slug',
    path: '/garments/$slug',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceMaterialsIndexRoute =
  AppAppWorkspaceMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceMaterialsIdRoute =
  AppAppWorkspaceMaterialsIdRouteImport.update({
    id: '/materials/$id',
    path: '/materials/$id',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceOperationsIndexRoute =
  AppAppWorkspaceOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceOrdersIndexRoute =
  AppAppWorkspaceOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceOrdersCodeRoute =
  AppAppWorkspaceOrdersCodeRouteImport.update({
    id: '/orders/$code',
    path: '/orders/$code',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceOrdersNewRoute =
  AppAppWorkspaceOrdersNewRouteImport.update({
    id: '/orders/new',
    path: '/orders/new',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceOrdersStagesRoute =
  AppAppWorkspaceOrdersStagesRouteImport.update({
    id: '/orders/stages',
    path: '/orders/stages',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceQuotationsIndexRoute =
  AppAppWorkspaceQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)
const AppAppWorkspaceQuotationsSlugRoute =
  AppAppWorkspaceQuotationsSlugRouteImport.update({
    id: '/quotations/$slug',
    path: '/quotations/$slug',
    getParentRoute: () => AppAppWorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRouteWithChildren
  '/app': typeof AppAppRouteRouteWithChildren
  '/uploads/$': typeof UploadsSplatRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/auth/$path': typeof AppAuthPathRoute
  '/organization/$path': typeof AppOrganizationPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/admin/$path': typeof AppAppAdminPathRoute
  '/app/settings/$path': typeof AppAppSettingsPathRoute
  '/app/': typeof AppAppWorkspaceIndexRoute
  '/app/clients/$id': typeof AppAppWorkspaceClientsIdRoute
  '/app/garments/$slug': typeof AppAppWorkspaceGarmentsSlugRoute
  '/app/materials/$id': typeof AppAppWorkspaceMaterialsIdRoute
  '/app/orders/$code': typeof AppAppWorkspaceOrdersCodeRoute
  '/app/orders/new': typeof AppAppWorkspaceOrdersNewRoute
  '/app/orders/stages': typeof AppAppWorkspaceOrdersStagesRoute
  '/app/quotations/$slug': typeof AppAppWorkspaceQuotationsSlugRoute
  '/app/clients/': typeof AppAppWorkspaceClientsIndexRoute
  '/app/garments/': typeof AppAppWorkspaceGarmentsIndexRoute
  '/app/materials/': typeof AppAppWorkspaceMaterialsIndexRoute
  '/app/operations/': typeof AppAppWorkspaceOperationsIndexRoute
  '/app/orders/': typeof AppAppWorkspaceOrdersIndexRoute
  '/app/quotations/': typeof AppAppWorkspaceQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteRouteWithChildren
  '/app': typeof AppAppWorkspaceIndexRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/auth/$path': typeof AppAuthPathRoute
  '/organization/$path': typeof AppOrganizationPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/admin/$path': typeof AppAppAdminPathRoute
  '/app/settings/$path': typeof AppAppSettingsPathRoute
  '/app/clients/$id': typeof AppAppWorkspaceClientsIdRoute
  '/app/garments/$slug': typeof AppAppWorkspaceGarmentsSlugRoute
  '/app/materials/$id': typeof AppAppWorkspaceMaterialsIdRoute
  '/app/orders/$code': typeof AppAppWorkspaceOrdersCodeRoute
  '/app/orders/new': typeof AppAppWorkspaceOrdersNewRoute
  '/app/orders/stages': typeof AppAppWorkspaceOrdersStagesRoute
  '/app/quotations/$slug': typeof AppAppWorkspaceQuotationsSlugRoute
  '/app/clients': typeof AppAppWorkspaceClientsIndexRoute
  '/app/garments': typeof AppAppWorkspaceGarmentsIndexRoute
  '/app/materials': typeof AppAppWorkspaceMaterialsIndexRoute
  '/app/operations': typeof AppAppWorkspaceOperationsIndexRoute
  '/app/orders': typeof AppAppWorkspaceOrdersIndexRoute
  '/app/quotations': typeof AppAppWorkspaceQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/app': typeof AppAppRouteRouteWithChildren
  '/uploads/$': typeof UploadsSplatRoute
  '/_app/app/_workspace': typeof AppAppWorkspaceRouteRouteWithChildren
  '/_app/app/onboarding': typeof AppAppOnboardingRoute
  '/_app/auth/$path': typeof AppAuthPathRoute
  '/_app/organization/$path': typeof AppOrganizationPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/app/admin/$path': typeof AppAppAdminPathRoute
  '/_app/app/settings/$path': typeof AppAppSettingsPathRoute
  '/_app/app/_workspace/': typeof AppAppWorkspaceIndexRoute
  '/_app/app/_workspace/clients/$id': typeof AppAppWorkspaceClientsIdRoute
  '/_app/app/_workspace/garments/$slug': typeof AppAppWorkspaceGarmentsSlugRoute
  '/_app/app/_workspace/materials/$id': typeof AppAppWorkspaceMaterialsIdRoute
  '/_app/app/_workspace/orders/$code': typeof AppAppWorkspaceOrdersCodeRoute
  '/_app/app/_workspace/orders/new': typeof AppAppWorkspaceOrdersNewRoute
  '/_app/app/_workspace/orders/stages': typeof AppAppWorkspaceOrdersStagesRoute
  '/_app/app/_workspace/quotations/$slug': typeof AppAppWorkspaceQuotationsSlugRoute
  '/_app/app/_workspace/clients/': typeof AppAppWorkspaceClientsIndexRoute
  '/_app/app/_workspace/garments/': typeof AppAppWorkspaceGarmentsIndexRoute
  '/_app/app/_workspace/materials/': typeof AppAppWorkspaceMaterialsIndexRoute
  '/_app/app/_workspace/operations/': typeof AppAppWorkspaceOperationsIndexRoute
  '/_app/app/_workspace/orders/': typeof AppAppWorkspaceOrdersIndexRoute
  '/_app/app/_workspace/quotations/': typeof AppAppWorkspaceQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/uploads/$'
    | '/app/onboarding'
    | '/auth/$path'
    | '/organization/$path'
    | '/api/auth/$'
    | '/app/admin/$path'
    | '/app/settings/$path'
    | '/app/'
    | '/app/clients/$id'
    | '/app/garments/$slug'
    | '/app/materials/$id'
    | '/app/orders/$code'
    | '/app/orders/new'
    | '/app/orders/stages'
    | '/app/quotations/$slug'
    | '/app/clients/'
    | '/app/garments/'
    | '/app/materials/'
    | '/app/operations/'
    | '/app/orders/'
    | '/app/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/uploads/$'
    | '/app/onboarding'
    | '/auth/$path'
    | '/organization/$path'
    | '/api/auth/$'
    | '/app/admin/$path'
    | '/app/settings/$path'
    | '/app/clients/$id'
    | '/app/garments/$slug'
    | '/app/materials/$id'
    | '/app/orders/$code'
    | '/app/orders/new'
    | '/app/orders/stages'
    | '/app/quotations/$slug'
    | '/app/clients'
    | '/app/garments'
    | '/app/materials'
    | '/app/operations'
    | '/app/orders'
    | '/app/quotations'
  id:
    | '__root__'
    | '/_app'
    | '/_app/app'
    | '/uploads/$'
    | '/_app/app/_workspace'
    | '/_app/app/onboarding'
    | '/_app/auth/$path'
    | '/_app/organization/$path'
    | '/api/auth/$'
    | '/_app/app/admin/$path'
    | '/_app/app/settings/$path'
    | '/_app/app/_workspace/'
    | '/_app/app/_workspace/clients/$id'
    | '/_app/app/_workspace/garments/$slug'
    | '/_app/app/_workspace/materials/$id'
    | '/_app/app/_workspace/orders/$code'
    | '/_app/app/_workspace/orders/new'
    | '/_app/app/_workspace/orders/stages'
    | '/_app/app/_workspace/quotations/$slug'
    | '/_app/app/_workspace/clients/'
    | '/_app/app/_workspace/garments/'
    | '/_app/app/_workspace/materials/'
    | '/_app/app/_workspace/operations/'
    | '/_app/app/_workspace/orders/'
    | '/_app/app/_workspace/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/_workspace': {
      id: '/_app/app/_workspace'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAppWorkspaceRouteRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/onboarding': {
      id: '/_app/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppAppOnboardingRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/auth/$path': {
      id: '/_app/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AppAuthPathRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organization/$path': {
      id: '/_app/organization/$path'
      path: '/organization/$path'
      fullPath: '/organization/$path'
      preLoaderRoute: typeof AppOrganizationPathRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/_workspace/': {
      id: '/_app/app/_workspace/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppWorkspaceIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/admin/$path': {
      id: '/_app/app/admin/$path'
      path: '/admin/$path'
      fullPath: '/app/admin/$path'
      preLoaderRoute: typeof AppAppAdminPathRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/settings/$path': {
      id: '/_app/app/settings/$path'
      path: '/settings/$path'
      fullPath: '/app/settings/$path'
      preLoaderRoute: typeof AppAppSettingsPathRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/_workspace/clients/': {
      id: '/_app/app/_workspace/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppAppWorkspaceClientsIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/clients/$id': {
      id: '/_app/app/_workspace/clients/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppAppWorkspaceClientsIdRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/garments/': {
      id: '/_app/app/_workspace/garments/'
      path: '/garments'
      fullPath: '/app/garments/'
      preLoaderRoute: typeof AppAppWorkspaceGarmentsIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/garments/$slug': {
      id: '/_app/app/_workspace/garments/$slug'
      path: '/garments/$slug'
      fullPath: '/app/garments/$slug'
      preLoaderRoute: typeof AppAppWorkspaceGarmentsSlugRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/materials/': {
      id: '/_app/app/_workspace/materials/'
      path: '/materials'
      fullPath: '/app/materials/'
      preLoaderRoute: typeof AppAppWorkspaceMaterialsIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/materials/$id': {
      id: '/_app/app/_workspace/materials/$id'
      path: '/materials/$id'
      fullPath: '/app/materials/$id'
      preLoaderRoute: typeof AppAppWorkspaceMaterialsIdRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/operations/': {
      id: '/_app/app/_workspace/operations/'
      path: '/operations'
      fullPath: '/app/operations/'
      preLoaderRoute: typeof AppAppWorkspaceOperationsIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/orders/': {
      id: '/_app/app/_workspace/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppAppWorkspaceOrdersIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/orders/$code': {
      id: '/_app/app/_workspace/orders/$code'
      path: '/orders/$code'
      fullPath: '/app/orders/$code'
      preLoaderRoute: typeof AppAppWorkspaceOrdersCodeRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/orders/new': {
      id: '/_app/app/_workspace/orders/new'
      path: '/orders/new'
      fullPath: '/app/orders/new'
      preLoaderRoute: typeof AppAppWorkspaceOrdersNewRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/orders/stages': {
      id: '/_app/app/_workspace/orders/stages'
      path: '/orders/stages'
      fullPath: '/app/orders/stages'
      preLoaderRoute: typeof AppAppWorkspaceOrdersStagesRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/quotations/': {
      id: '/_app/app/_workspace/quotations/'
      path: '/quotations'
      fullPath: '/app/quotations/'
      preLoaderRoute: typeof AppAppWorkspaceQuotationsIndexRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
    '/_app/app/_workspace/quotations/$slug': {
      id: '/_app/app/_workspace/quotations/$slug'
      path: '/quotations/$slug'
      fullPath: '/app/quotations/$slug'
      preLoaderRoute: typeof AppAppWorkspaceQuotationsSlugRouteImport
      parentRoute: typeof AppAppWorkspaceRouteRoute
    }
  }
}

interface AppAppWorkspaceRouteRouteChildren {
  AppAppWorkspaceIndexRoute: typeof AppAppWorkspaceIndexRoute
  AppAppWorkspaceClientsIdRoute: typeof AppAppWorkspaceClientsIdRoute
  AppAppWorkspaceGarmentsSlugRoute: typeof AppAppWorkspaceGarmentsSlugRoute
  AppAppWorkspaceMaterialsIdRoute: typeof AppAppWorkspaceMaterialsIdRoute
  AppAppWorkspaceOrdersCodeRoute: typeof AppAppWorkspaceOrdersCodeRoute
  AppAppWorkspaceOrdersNewRoute: typeof AppAppWorkspaceOrdersNewRoute
  AppAppWorkspaceOrdersStagesRoute: typeof AppAppWorkspaceOrdersStagesRoute
  AppAppWorkspaceQuotationsSlugRoute: typeof AppAppWorkspaceQuotationsSlugRoute
  AppAppWorkspaceClientsIndexRoute: typeof AppAppWorkspaceClientsIndexRoute
  AppAppWorkspaceGarmentsIndexRoute: typeof AppAppWorkspaceGarmentsIndexRoute
  AppAppWorkspaceMaterialsIndexRoute: typeof AppAppWorkspaceMaterialsIndexRoute
  AppAppWorkspaceOperationsIndexRoute: typeof AppAppWorkspaceOperationsIndexRoute
  AppAppWorkspaceOrdersIndexRoute: typeof AppAppWorkspaceOrdersIndexRoute
  AppAppWorkspaceQuotationsIndexRoute: typeof AppAppWorkspaceQuotationsIndexRoute
}

const AppAppWorkspaceRouteRouteChildren: AppAppWorkspaceRouteRouteChildren = {
  AppAppWorkspaceIndexRoute: AppAppWorkspaceIndexRoute,
  AppAppWorkspaceClientsIdRoute: AppAppWorkspaceClientsIdRoute,
  AppAppWorkspaceGarmentsSlugRoute: AppAppWorkspaceGarmentsSlugRoute,
  AppAppWorkspaceMaterialsIdRoute: AppAppWorkspaceMaterialsIdRoute,
  AppAppWorkspaceOrdersCodeRoute: AppAppWorkspaceOrdersCodeRoute,
  AppAppWorkspaceOrdersNewRoute: AppAppWorkspaceOrdersNewRoute,
  AppAppWorkspaceOrdersStagesRoute: AppAppWorkspaceOrdersStagesRoute,
  AppAppWorkspaceQuotationsSlugRoute: AppAppWorkspaceQuotationsSlugRoute,
  AppAppWorkspaceClientsIndexRoute: AppAppWorkspaceClientsIndexRoute,
  AppAppWorkspaceGarmentsIndexRoute: AppAppWorkspaceGarmentsIndexRoute,
  AppAppWorkspaceMaterialsIndexRoute: AppAppWorkspaceMaterialsIndexRoute,
  AppAppWorkspaceOperationsIndexRoute: AppAppWorkspaceOperationsIndexRoute,
  AppAppWorkspaceOrdersIndexRoute: AppAppWorkspaceOrdersIndexRoute,
  AppAppWorkspaceQuotationsIndexRoute: AppAppWorkspaceQuotationsIndexRoute,
}

const AppAppWorkspaceRouteRouteWithChildren =
  AppAppWorkspaceRouteRoute._addFileChildren(AppAppWorkspaceRouteRouteChildren)

interface AppAppRouteRouteChildren {
  AppAppWorkspaceRouteRoute: typeof AppAppWorkspaceRouteRouteWithChildren
  AppAppOnboardingRoute: typeof AppAppOnboardingRoute
  AppAppAdminPathRoute: typeof AppAppAdminPathRoute
  AppAppSettingsPathRoute: typeof AppAppSettingsPathRoute
}

const AppAppRouteRouteChildren: AppAppRouteRouteChildren = {
  AppAppWorkspaceRouteRoute: AppAppWorkspaceRouteRouteWithChildren,
  AppAppOnboardingRoute: AppAppOnboardingRoute,
  AppAppAdminPathRoute: AppAppAdminPathRoute,
  AppAppSettingsPathRoute: AppAppSettingsPathRoute,
}

const AppAppRouteRouteWithChildren = AppAppRouteRoute._addFileChildren(
  AppAppRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAppRouteRoute: typeof AppAppRouteRouteWithChildren
  AppAuthPathRoute: typeof AppAuthPathRoute
  AppOrganizationPathRoute: typeof AppOrganizationPathRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppRouteRoute: AppAppRouteRouteWithChildren,
  AppAuthPathRoute: AppAuthPathRoute,
  AppOrganizationPathRoute: AppOrganizationPathRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
